import { getLabel } from './label';

export const infectiousJson = (data: unknown) => ({
  sheet: getLabel('infectious'),
  columns: [
    { label: getLabel('record'), value: 'id' },
    { label: getLabel('patient'), value: 'patient_id' },
    { label: getLabel('check_date'), value: 'date' },
    { label: getLabel('infection_type'), value: (row: unknown) => getLabel(row.infection_type) },
    { label: getLabel('infection_start_date'), value: 'infection_start_date' },
    { label: getLabel('infection_end_date'), value: 'infection_end_date' },
    { label: getLabel('staphylococcus'), value: 'staphylococcus' },
    { label: getLabel('streptococcus'), value: 'streptococcus' },
    { label: getLabel('intestinal_stick'), value: 'intestinal_stick' },
    { label: getLabel('pseudomona'), value: 'pseudomona' },
    { label: getLabel('enterococcus'), value: 'enterococcus' },
    { label: getLabel('candida'), value: 'candida' },
    { label: getLabel('other'), value: 'other' },
    { label: getLabel('other_comment'), value: 'other_comment' },
    { label: getLabel('treatment_start_date'), value: 'treatment_start_date' },
    { label: getLabel('treatment_end_date'), value: 'treatment_end_date' },
    { label: getLabel('vancomycin'), value: 'vancomycin' },
    { label: getLabel('ceftazidime'), value: 'ceftazidime' },
    { label: getLabel('ceftriaxone'), value: 'ceftriaxone' },
    { label: getLabel('cefepime'), value: 'cefepime' },
    { label: getLabel('meropenem'), value: 'meropenem' },
    { label: getLabel('imipenem'), value: 'imipenem' },
    { label: getLabel('ciprofloxacin'), value: 'ciprofloxacin' },
    { label: getLabel('cefazolin'), value: 'cefazolin' },
    { label: getLabel('gentamicin'), value: 'gentamicin' },
    { label: getLabel('clindamycin'), value: 'clindamycin' },
    { label: getLabel('rifampicin'), value: 'rifampicin' },
    { label: getLabel('rluconazole'), value: 'rluconazole' },
  ],
  content: [...data],
});
