name: Deploy to DigitalOcean
on:
  push:
    branches: [main] # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.PORT }}" \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/sev/www/ge-msps-next/

      - name: Setup and start application
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "\
            cd /home/sev/www/ge-msps-next && \
            export NVM_DIR=\$HOME/.nvm && \
            [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh && \
            npm install && \
            sudo npm install -g pm2 && \
            npm run build && \
            pm2 describe ge-msps-next > /dev/null && \
            pm2 reload ecosystem.config.js || \
            pm2 start ecosystem.config.js && \
            pm2 save"
